name: Zotero Bib Export

on:
  schedule:
    - cron: '0 12 * * *'  # täglich um 12:00 Uhr UTC
  workflow_dispatch:      # manuell auslösbar

jobs:
  export-bib:
    permissions:
          contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download latest BibTeX from Zotero
      run: |
        curl -L -o references.bib "https://api.zotero.org/groups/${{ secrets.ZOTERO_GROUP_ID }}/collections/ZCUUTPNW/items?format=bibtex&key=${{ secrets.ZOTERO_API_KEY }}"

    - name: Commit changes
      run: |
        git add references.bib
        git -c user.email="${{ secrets.EMAIL }}" -c user.name="${{ secrets.USERNAME }}" commit -am "Automatisches Update der .bib-Datei von Zotero" || echo "Keine Änderungen zum Commit"
    
    - name: Push change to repo
      run: git push origin main
